CricketWebsite/CricketWebsite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cric/',include('cric.urls'))
]

CricketWebsite/cric/urls.py
from django.urls import path
from . import views


app_name='cric'
urlpatterns=[
    path('',views.home,name="home"),
    path('current-fixtures',views.index,name="index"),
    path('series/<int:series_id>/',views.seriesDisplay,name="series"),
    path('live-matches/',views.liveMatchesList,name="liveMatches"),
    path('series-list/',views.displaySeriesList,name="Series-List"),
    path('teams-list/',views.displayTeams,name="Teams-List"),
    path('series/<int:series_id>/teams-list/<int:team_id>/',views.TeamDisplay,name="Team"),

]

CricketWebsite/cric/models.py
from django.db import models

# Create your models here.

CricketWebsite/cric/views.py
from django.http import Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
import requests
import numpy as np
import time
import json
#from django.http import HttpResponse
#from django.template import loader

# Create your views here.

def live_series_matches(single_series,liveSeries_matches,matches):
    for j in matches:
        singleMatch_dict = {}
        if single_series['Series_Id'] == j['series_id']:
                singleMatch_dict['Match_Id'] = j['match_id']
                singleMatch_dict['State'] = j['header']['state_title']
                singleMatch_dict['Desc'] = j['header']['match_desc']
                singleMatch_dict['Details']='https://www.cricbuzz.com/cricket-scores/{0}'.format(j['match_id'])
                if j['header']['toss'] != '':
                    singleMatch_dict['Toss'] = j['header']['toss']
                singleMatch_dict['Team1'] = j['team1']['name']
                singleMatch_dict['Team1_Id'] = j['team1']['id']
                singleMatch_dict['Team2'] = j['team2']['name']
                singleMatch_dict['Team2_Id'] = j['team2']['id']
                singleMatch_dict['Status'] = j['header']['status']
                if j['header']['state'] == 'inprogress' or j['header']['state'] == 'rain':
                    if singleMatch_dict['Team1_Id'] == j['bat_team']['id']:
                        singleMatch_dict['Batting_Team']=singleMatch_dict['Team1']

                    else:
                        singleMatch_dict['Batting_Team'] = singleMatch_dict['Team2']
                    singleMatch_dict['Batting_Score'] = j['bat_team']['innings'][len(j['bat_team']['innings'])-1]['score']
                    singleMatch_dict['Batting_Wkts'] = j['bat_team']['innings'][len(j['bat_team']['innings'])-1]['wkts']
                    singleMatch_dict['Batting_Overs'] = j['bat_team']['innings'][len(j['bat_team']['innings'])-1]['overs']

                liveSeries_matches = np.append(liveSeries_matches, singleMatch_dict)
    return liveSeries_matches


url="http://mapps.cricbuzz.com/cbzios/match/livematches"
def get_live_matches():
    mat = requests.get(url).json()
    matches = mat['matches']
    series_list = np.array([])
    series_list = [x['series_id'] for x in matches]
    series_list = list(set(series_list))
    series_list.sort()
    series = np.array([])
    series_dict = {}
    for i in series_list:
        for j in matches:
            if i == j['series_id']:
                # series=np.append(series,[j['series_name']])
                series_dict['Series_Id'] = i
                series_dict['Series_Title'] = j['series_name']
                series = np.append(series, [series_dict.copy()])
                break

    for i in series:
        liveSeries_matches = np.array([])
        # liveSeries_matches=list(filter(lambda x:  x['series_id'] == i['Series_Id'] ,matches))
        liveSeries_matches = live_series_matches(i, liveSeries_matches, matches)
        i['Live_Matches'] = liveSeries_matches
    return series

def index(request):
    series_all=get_live_matches()
    return render(request,'cric/index.html',{'series_all':series_all})


def home(request):
    return render(request,'cric/home.html',{})

def setLive(current_matches):
    # print(type(current_matches))
    current_matches['Live_Matches']=list(filter(lambda x: x['State'] == "In Progress",current_matches['Live_Matches']))
    if len(current_matches['Live_Matches']) == 0:
        return False
    else:
        return True
def liveMatchesList(request):
    live_stream = get_live_matches()
    live_stream=list(filter(lambda x: setLive(x) == True,live_stream))

    if len(live_stream) == 0:
        return render(request,'cric/liveMatches.html',{'error': 'No Live Matches Right Now'})
    return render(request,'cric/liveMatches.html',{'live_stream':live_stream})

def seriesTeams(series_id):
    t_url="http://mapps.cricbuzz.com/cbzios/series/"+str(series_id)+"/teams"
    s_teams_data = requests.get(t_url).json()
    s_teams=s_teams_data['teams']
    s_teamsList=np.array([])
    for x in s_teams:
        team_data={}
        team_data['team_id']=x['id']
        team_data['Team_Name']=x['name']
        team_data['Series_Id']=series_id
        s_teamsList=np.append(s_teamsList,team_data)
    return s_teamsList

def seriesVenues(series_id):
    v_url = "http://mapps.cricbuzz.com/cbzios/series/" + str(series_id) + "/venues"
    s_venues_data = requests.get(v_url).json()
    s_venues = s_venues_data['venues']
    s_venuesList = np.array([])
    for x in s_venues:
        venue_data = {}
        venue_data['venue_id'] = x['id']
        venue_data['Venue_Name'] = x['name']
        venue_data['Venue_Location'] = x['location']
        venue_data['Venue_Country'] = x['country']
        venue_data['Venue_url'] = x['url'].replace('\\','')
        venue_data['Venue_img'] = x['img'].replace('\\','')
        s_venuesList = np.append(s_venuesList, venue_data)
    return s_venuesList

def seriesPointsTable(series_id):
    p_url="http://mapps.cricbuzz.com/cbzios/pointtable/" + str(series_id)
    s_points_data = requests.get(p_url).json()
    if len(s_points_data) == 0:
        return []
    s_point_group=s_points_data['group']
    s_point_group=list(s_point_group)
    s_point_group=s_point_group[0]
    s_points=s_points_data['group'][s_point_group]
    s_pointsList = np.array([])
    for x in s_points:
        points_dict={}
        points_dict['id'] = x['id']
        points_dict['Team'] = x['name']
        points_dict['played'] = x['p']
        points_dict['won'] = x['w']
        points_dict['lose'] = x['l']
        points_dict['tied'] = x['t']
        points_dict['nr'] = x['nr']
        points_dict['points'] = x['points']
        points_dict['nrr'] = x['nrr']
        s_pointsList = np.append(s_pointsList, points_dict)
    return s_pointsList

def checkHour(hr):
    if hr >= 12:
        dayState = 'PM'
        if hr > 12:
            hr = hr - 12

    else:
        dayState = "AM"
        if hr == 0:
            hr = 12
    return [dayState, hr]

def getdateTime(dt):
    dt=int(dt)
    hour = time.strftime('%H', time.localtime(dt))
    mint = time.strftime('%M', time.localtime(dt))

    hour = checkHour(int(hour))
    months=['January','February','March','April','May','June','July',
            'August','September','October','November','December']
    # matchDate = time.strftime('%m %d, %Y ', time.localtime(dt))
    day = time.strftime('%d', time.localtime(dt))
    month = time.strftime('%m', time.localtime(dt))
    year = time.strftime('%Y', time.localtime(dt))
    matchDate='{0} {1}, {2}'.format(months[int(month)],day,year)
    matchTime = '{0}:{1} {2}'.format(hour[1],mint,hour[0])
    return [matchDate,matchTime]


def seriesMatches(series_id):
    m_url = "http://mapps.cricbuzz.com/cbzios/series/" + str(series_id) + "/matches"
    s_matches_data = requests.get(m_url).json()
    s_matches=s_matches_data['matches']
    s_matchesList=np.array([])
    for x in s_matches:
        match_data={}
        match_data['Match_Id']=x['match_id']
        Date_Time=getdateTime(x['header']['start_time'])
        match_data['Match_Date']=Date_Time[0]
        match_data['Match_Time'] = Date_Time[1]
        match_data['Match_Desc']=x['header']['match_desc']
        match_data['Details']='https://www.cricbuzz.com/cricket-scores/{0}'.format(x['match_id'])
        match_data['Status']=x['header']['status']
        match_data['Venue_Name']=x['venue']['name']
        match_data['Venue_Location'] = x['venue']['location']
        match_data['Team1_Id']=x['team1']['id']
        match_data['Team1_Name'] = x['team1']['name']
        match_data['Team2_Id'] = x['team2']['id']
        match_data['Team2_Name'] = x['team2']['name']
        s_matchesList=np.append(s_matchesList,match_data)
    return s_matchesList
def seriesDisplay(request,series_id):
    series_url="http://mapps.cricbuzz.com/cbzios/series/" + str(series_id)
    series_data=requests.get(series_url).json()
    series_name=series_data['series']['name']
    s_teamsList  = seriesTeams(series_id)
    s_venuesList = seriesVenues(series_id)
    s_pointsList = seriesPointsTable(series_id)
    s_matchesList = seriesMatches(series_id)
    if len(s_pointsList) == 0:
        return render(request, 'cric/seriesPage.html', {'seriesName': series_name,'teams': s_teamsList,
                                                        'venues': s_venuesList,'matches': s_matchesList,
                                                        'points_error':'No Points Table Available'})
    return render(request,'cric/seriesPage.html',{'seriesName': series_name,'teams':s_teamsList,
                                                  'venues':s_venuesList,'matches': s_matchesList,
                                                  'pointsTable':s_pointsList})


def getSeriesList():
    s_list=requests.get(url).json()
    s_list=s_list['matches']
    # s_list=list(set(s_list))
    seriesList=np.array([])
    series_dict={
        'Series_Id': '2697',
        'Series_Name': 'ICC Cricket World Cup 2019'
    }
    seriesList=np.append(seriesList,series_dict)
    checkRepeat=[]
    for x in s_list:
        if x['series_id'] not in checkRepeat:
            series_dict={}
            series_dict['Series_Id']=x['series_id']
            series_dict['Series_Name']=x['series_name']
            checkRepeat.append(x['series_id'])
            seriesList=np.append(seriesList,series_dict)

    return seriesList

def displaySeriesList(request):
    seriesList=getSeriesList()
    return render(request, 'cric/seriesList.html', {'seriesList': seriesList})

def getTeams(teamsList,series_id):
    team_url="http://mapps.cricbuzz.com/cbzios/series/"+ series_id +"/teams"
    teams_list=requests.get(team_url).json()
    teams_list=teams_list['teams']
    for i in teams_list:
        team_data={}
        team_data['Team_Id']=i['id']
        team_data['Team_Name']=i['name']

CricketWebsite/cric/templates/cric/MatchPage.html
{% extends 'cric/base.html' %}

{% block body %}

<div class="container">

<p>{{Match}}</p>

</div>

{% endblock %}

CricketWebsite/cric/templates/cric/TeamPage.html
{% extends 'cric/base.html' %}

{% block body %}

<div class="container paddingContainer">

<h3 class="heading red-text">{{TeamName}}</h3>

<div class="row">
     {% for player in team %}
    <div class="col s12 m3">
      <div class="card">
        <div class="card-image">
          <img src="{{player.Pic_url}}" height="200">

        </div>
        <div class="card-content player_content">
            <span class="card-title">{{player.Name}}</span>
            <p>{{player.Role}}</p>
            <p>{{player.Style}}</p>
        </div>
        <div class="card-action">
          <a href={{player.Link}} target="_blank" class="btn btn-small red white-text right">Details</a>
            <div class="clearfix"></div>
        </div>
      </div>
    </div>
     {% endfor %}
  </div>

</div>

{% endblock %}

CricketWebsite/cric/templates/cric/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Cricket Website {% endblock %}</title>
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'cric/style.css' %}?{% now "U" %}">
    <link rel="shortcut icon" href="{% static 'cric/images/cric.png' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
<link href="https://fonts.googleapis.com/css?family=DM+Serif+Display|DM+Serif+Text|Lato|Oswald&display=swap" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
</head>
<body>
<div class="navigation navbar-fixed">
      <nav class="blue">
        <div class=" nav-wrapper row">
          <div class="col l2">

            <a href="{% url 'cric:index' %}" class="brand-logo">CricNode</a>
            <a href="#!" data-target="mobile-nav" class="sidenav-trigger">
              <i class="material-icons">menu</i>
            </a>
          </div>
          <ul id="nav-mobile" class="col l10 xl8 right hide-on-med-and-down">
            <li><a href="{% url 'cric:home' %}" class="nav_options">Home</a></li>
              <li><a href="{% url 'cric:index' %}" class="nav_options">Current Fixtures</a></li>
            <li><a href="{% url 'cric:liveMatches' %}" class="nav_options">Live Matches</a></li>
              <li><a href="{% url 'cric:Series-List' %}" class="nav_options">Series</a></li>
            <li><a href="{% url 'cric:Teams-List' %}" class="nav_options">Teams</a></li>
              <li><a href="{% url 'cric:series' 2697 %}" class="nav_options">ICC World Cup 2019</a></li>


          </ul>
        </div>

      </nav>
    </div>

    <!-- MOBILE NAV -->
    <div class="sidenav" id="mobile-nav">

      <span><i class="material-icons closing right">close</i></span>
      <div class="clearfix"></div>
      <ul class=" collection">
        <li class="blue collection-item"><a href="{% url 'cric:home' %}" class="nav_options">Home</a></li>
          <li class="blue collection-item"><a href="{% url 'cric:index' %}" class="nav_options">Current Fixtures</a></li>
          <li class="blue collection-item"><a href="{% url 'cric:liveMatches' %}" class="nav_options">Live Matches</a></li>
          <li class="blue collection-item"><a href="{% url 'cric:Series-List' %}" class="nav_options">Series</a></li>
          <li class="blue collection-item"><a href="{% url 'cric:Teams-List' %}" class="nav_options">Teams</a></li>
          <li class="blue collection-item"><a href="{% url 'cric:series' 2697 %}" class="nav_options">ICC World Cup 2019</a></li>
      </ul>
    </div>

    {% block body %}
    {% endblock %}
</body>
<script>
    $(document).ready(function () {
    $('.sidenav')
      .sidenav()
      .on('click tap', '.closing', () => {
        $('.sidenav').sidenav('close');
      });
          $('.tabs').tabs({
          swipeable: false
          });

  });
</script>
</html>

CricketWebsite/cric/templates/cric/home.html
{% extends 'cric/base.html' %}
{% block title %} CricNode {% endblock %}
{% block body %}

<div class="container paddingContainer center z-depth-1">
    <h1 class="blue-text heading mainHeading animatedHead">Welcome To CricNode</h1>
    <div class="leadAnimated lead">
    <p class="white-text">The app created to simplify the usage of the data which is generated by CricBuzz</p>
    <p class="white-text">We have the potential to take it to a Large Level.. Just the game of trust that the goals will be achieved</p>
        </div>
</div>

{% endblock %}

CricketWebsite/cric/templates/cric/index.html
{% extends 'cric/base.html' %}

{% block body %}
<div class="container paddingContainer">
<h2 class="blue-text heading center animatedHead">Current Matches And Fixtures</h2>
<ul >
{% for series in series_all %}

    <li>
        <h4 ><a href="{% url 'cric:series' series.Series_Id %}" class="heading red-text text-lighten-2 fromLeft">{{series.Series_Title}}</a></h4>

<div class="row fromRight">


            {% for match in series.Live_Matches %}

        <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{match.Team1}} vs {{match.Team2}}</span>
          <p>{{match.Desc}}</p>
            {% if match.Toss %}

            <p>Toss: {{match.Toss}}</p>
            {% endif %}

            {% if match.Batting_Team %}

            <p class="left">{{match.Batting_Team}}</p>

            <p class="right">{{match.Batting_Score}}/{{match.Batting_Wkts}} ({{match.Batting_Overs}})</p>
            <p class="clearfix"></p>
            {% endif %}
            <p>{{match.State}}</p>
            <p>{{match.Status}}</p>
        </div>
        <div class="card-action">
          <a href="{{match.Details}}" target="_blank">Match Details</a>

        </div>
      </div>
    </div>
            {% endfor %}
    </div>
    </li>
{% endfor %}
</ul>
</div>

{% endblock %}

CricketWebsite/cric/templates/cric/liveMatches.html
{% extends 'cric/base.html' %}


{% block body %}
<div class="container paddingContainer">
<h2 class="blue-text heading center animatedHead">Live Matches</h2>
    {% if error %}
    <br>
    <br>
    <h4 class="heading center red-text leadAnimated">**{{error}}**</h4>
    {% endif %}

    {% for series in live_stream %}

    <li>
        <h4 ><a href="{% url 'cric:series' series.Series_Id %}" class="heading red-text text-lighten-2 fromLeft">{{series.Series_Title}}</a></h4>

<div class="row fromRight">


            {% for match in series.Live_Matches %}

        <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">{{match.Team1}} vs {{match.Team2}}</span>
          <p>{{match.Desc}}</p>
            {% if match.Toss %}

            <p>Toss: {{match.Toss}}</p>
            {% endif %}

            {% if match.Batting_Team %}

            <p class="left">{{match.Batting_Team}}</p>

            <p class="right">{{match.Batting_Score}}/{{match.Batting_Wkts}} ({{match.Batting_Overs}})</p>
            <p class="clearfix"></p>
            {% endif %}
            <p>{{match.State}}</p>
            <p>{{match.Status}}</p>
        </div>
        <div class="card-action">
          <a href="{{match.Details}}" target="_blank">Match Details</a>

        </div>
      </div>
    </div>
            {% endfor %}
    </div>
    </li>
{% endfor %}

</div>
{% endblock %}

CricketWebsite/cric/templates/cric/seriesList.html
{% extends 'cric/base.html' %}

{% block body %}

<div class="container paddingContainer">
    <h2 class="blue-text heading center animatedHead">List Of Series</h2>
    <div class="container">
    <ul class="collection center leadAnimated">
        {% for sr in seriesList %}
        <li class="collection-item">
            <a href="{% url 'cric:series' sr.Series_Id %}" class="heading">{{sr.Series_Name}}</a>
        </li>
        {% endfor %}
    </ul>
</div>
</div>

{% endblock %}

CricketWebsite/cric/templates/cric/seriesPage.html
{% extends 'cric/base.html' %}
{% block title %}
Series
{% endblock %}

{% block body %}

<br>
<div class="container paddingContainer z-depth-1 seriesContainer">
    <h2 class="blue-text heading center animatedHead">{{seriesName}}</h2>
<div class="row">
    <div class="col s12">
      <ul class="tabs">
        <li class="tab col s3"><a href="#schedule">Schedule</a></li>
        <li class="tab col s3"><a href="#teams" >Teams</a></li>

        <li class="tab col s3"><a href="#venues" class="active">Venues</a></li>
        {% if points_error %}
        <li class="tab col s3 disabled"><a href="#pointsTable">Points Table</a></li>
        {% else %}
        <li class="tab col s3"><a href="#pointsTable">Points Table</a></li>
        {% endif %}
      </ul>
    </div>
    <div id="schedule" class="col s12">
<h2 class="heading red-text center leadAnimated">Matches Schedule</h2>
        <table class="highlight striped white paddingContainer">
        <thead>
          <tr>
              <th>Date</th>
              <th>Time</th>
              <th>Match Details</th>
              <th>Venue</th>
          </tr>
        </thead>

        <tbody>
        {% for match in matches %}
          <tr>
            <td>{{match.Match_Date}}</td>
            <td>{{match.Match_Time}}</td>
            <td>
                <h6>{{match.Team1_Name}} vs {{match.Team2_Name}}, {{match.Match_Desc}}</h6>
                <p class="red-text"><a href="{{match.Details}}" target="_blank">{{match.Status}}</a></p>
            </td>
            <td>{{match.Venue_Name}} {{match.Venue_Location}}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    </div>
    <div id="teams" class="col s12">
        <br>
        <h2 class="heading red-text center leadAnimated">Teams</h2>
        <ul class="collection container center">
            {% for team in teams %}
            <li class="collection-item"><a href="{% url 'cric:Team' team.Series_Id team.team_id %}">{{team.Team_Name}}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div id="venues" class="col s12 container">
<h2 class="heading red-text center leadAnimated">Venues</h2>
<br>

 <div class="row">
     {% for venue in venues %}
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
          <img src="{{venue.Venue_img}}" height="300">

        </div>
        <div class="card-content venue_content">
            <span class="card-title">{{venue.Venue_Name}}</span>
            <p>{{venue.Venue_Location}}</p>
        </div>
        <div class="card-action">
          <a href={{venue.Venue_url}}" target="_blank" class="btn btn-small red white-text right">Details</a>
            <div class="clearfix"></div>
        </div>
      </div>
    </div>
     {% endfor %}
  </div>



    </div>
    <div id="pointsTable" class="col s12">
<h2 class="heading red-text center leadAnimated">Points Table</h2>
        <!--{% if points_error %}-->
        <!--<h4 class="heading">{{points_error}}</h4>-->

        <!--{% else %}-->
        <div class="card white black-text points_table">

            <table>
                 <thead class="grey">
          <tr>
              <th colspan="10">Teams</th>
              <th>Match</th>
              <th>Won</th>
              <th>Lost</th>
              <th>Teid</th>
              <th>NR</th>
              <th>Pts</th>
              <th>NRR</th>
          </tr>
        </thead>

        <tbody>
        {% for points in pointsTable %}
          <tr>
            <td class="blue-text" colspan="10">{{points.Team}}</td>
            <td>{{points.played}}</td>
            <td>{{points.won}}</td>
            <td>{{points.lose}}</td>
            <td>{{points.tied}}</td>
            <td>{{points.nr}}</td>
            <td>{{points.points}}</td>
            <td>{{points.nrr}}</td>
          </tr>
        {% endfor %}
                  </tbody>
                </table>

        </div>
        <!--{% endif %}-->
    </div>
  </div>

</div>
{% endblock %}

CricketWebsite/cric/templates/cric/teams-list.html
{% extends 'cric/base.html' %}

{% block body %}

<div class="container paddingContainer">

    <h2 class="blue-text heading center animatedHead">Teams</h2>
<table class="highlight container striped white">
        <thead>
          <tr>
              <th>Teams</th>
              <th class="right">Captains</th>

          </tr>
        </thead>

        <tbody>
        {% for team in teamsList %}
          <tr>

            <td><a href="{% url 'cric:Team' team.Series_Id team.Team_Id %}">{{team.Team_Name}}</a></td>
            <td class="right">{{team.Team_Captain}}</td>

          </tr>
        {% endfor %}
        </tbody>
      </table>
</div>

{% endblock %}